### ISSUE TITLE
Draggable Symbol does not work

### ISSUE THREAD

**Issue by karianpour** [map-ir/mapir-flutter-map-sdk#2] opened 2020-02-04 13:37 UTC
The draggable symbol is not working on iPhone 11 ( The simulator I have ) also it does not work on my Android phone, but draggable circle works on android, so I guess the code is correct.

- Flutter 1.12.13+hotfix.5
- Engine • revision 2994f7e1e6
- Tools • Dart 2.7.0
- Simulator : Version 11.3.1 (SimulatorApp-912.5.1 SimulatorKit-570.3 CoreSimulator-681.17.2)

**Comment by Mr-Alirezaa** [comment] 2020-02-08 06:12
@karianpour 
Hi, This issue is duplicate of #1 
So, I'll close it.

**Closed as completed by Mr-Alirezaa** 2020-02-08 06:12 UTC
Labels: duplicate
